site_name: Luke Albarracin
nav:
- 'About Me' : index.md
- 'Projects' : projects.md

# theme:
#     name: material
#     highlightjs: true
#     hljs_languages:
#        - yaml
#        - rust
#        - clojure
